export const CREATE_MEMBER = "CREATE_MEMBER"
export const RETRIEVE_MEMBERS = "RETRIEVE_MEMBERS";
export const UPDATE_MEMBER = "UPDATE_MEMBER";
export const DELETE_MEMBER = "DELETE_MEMBER";
export const BELONGTO_MEMBER = "BELONGTO_MEMBER";

export const CREATE_TEAM = "CREATE_TEAM"
export const RETRIEVE_TEAMS = "RETRIEVE_TEAMS";
export const UPDATE_TEAM = "UPDATE_TEAM";
export const DELETE_TEAM = "DELETE_TEAM";
